import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

class ReportService:
    @staticmethod
    def generate_pdf_report(report_data: dict, output_filename: str) -> str:
        os.makedirs("reports", exist_ok=True)
        file_path = os.path.join("reports", output_filename)
        
        doc = SimpleDocTemplate(file_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story = []
        styles = getSampleStyleSheet()

        # Styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=20,
            textColor=colors.HexColor('#050B18'),
            spaceAfter=12
        )
        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#0B3B60'),
            spaceAfter=18
        )
        h2_style = ParagraphStyle(
            'SectionH2',
            parent=styles['Heading2'],
            fontSize=13,
            textColor=colors.HexColor('#0B3B60'),
            spaceBefore=10,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            fontSize=9.5,
            textColor=colors.HexColor('#1E293B'),
            leading=13
        )

        # Header
        story.append(Paragraph("PortIN — Intelligent Maritime Freight Intelligence Platform", title_style))
        story.append(Paragraph(f"Official SIH 2026 Problem Statement 26006 | SAIL & Ministry of Steel | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", subtitle_style))
        story.append(Spacer(1, 8))

        # Executive Summary Box
        summary_text = report_data.get("summary", "Automated executive chartering analysis generated by the PortIN optimization platform.")
        story.append(Paragraph("1. Executive Summary", h2_style))
        story.append(Paragraph(summary_text, body_style))
        story.append(Spacer(1, 10))

        # Key Parameters Table
        story.append(Paragraph("2. Operational Chartering Parameters", h2_style))
        table_data = [
            ["Parameter", "Evaluated Value", "Source Provenance"],
            ["Cargo Commodity", report_data.get("cargo_type", "Coking Coal"), "SAIL Blast Furnace Specification"],
            ["Parcel Size", f"{report_data.get('cargo_mt', 70000):,.0f} MT", "Procurement Requirement"],
            ["Trade Lane", f"{report_data.get('origin_country', 'Australia')} -> {report_data.get('destination_port', 'Paradip')}", "Major Maritime Bulk Corridor"],
            ["Recommended Vessel", report_data.get("recommended_vessel", "Panamax"), "Physical Berth Optimization"],
            ["Contract Strategy", report_data.get("contract_type", "Short-Term Multi-Voyage (3 Voyages COA)"), "Volatilty Mitigation Model"],
            ["Market Signal", report_data.get("market_signal", "BOOK NOW"), "HistGradientBoosting Model"],
            ["Optimal Entry Window", report_data.get("optimal_window", "Next 7-14 Days"), "Forward Freight Curve Analysis"],
            ["Estimated Total Cost", f"${report_data.get('estimated_total_cost_usd', 1850000):,.2f} USD", "Aggregated Chartering Model"],
            ["Operational Risk", f"{report_data.get('risk_score', 24.5)} / 100 (LOW)", "Multi-Factor Risk Engine"]
        ]
        
        t = Table(table_data, colWidths=[150, 180, 190])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#081426')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#F8FBFF')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F1F5F9')])
        ]))
        story.append(t)
        story.append(Spacer(1, 14))

        # PortIN Decision Twin Plans
        story.append(Paragraph("3. PortIN Decision Twin Strategy Evaluation", h2_style))
        plan_desc = (
            "The Decision Twin ran 36 stochastic perturbations simulating variations across weather, "
            "berth queues, and bunker rates. Plan A is recommended as the optimum balance of volume savings "
            "and draft safety."
        )
        story.append(Paragraph(plan_desc, body_style))
        story.append(Spacer(1, 8))

        twin_data = [
            ["Plan", "Strategy", "Vessel", "Rate ($/MT)", "Est. Idle (Days)", "Risk"],
            ["Plan A (Best Overall)", "Short-Term Multi-Voyage (3x)", "Panamax", "$14.15", "5.4 days", "24.5 (Low)"],
            ["Plan B (Lowest Risk)", "Spot with Guaranteed Berth", "Supramax", "$15.95", "3.3 days", "14.0 (Very Low)"],
            ["Plan C (Lowest Cost)", "Long-Term Strategic COA", "Capesize / Panamax", "$13.05", "8.4 days", "52.0 (Medium)"]
        ]
        t2 = Table(twin_data, colWidths=[110, 130, 80, 75, 75, 50])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0B3B60')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ]))
        story.append(t2)
        story.append(Spacer(1, 14))

        # Legal & Truthfulness Disclaimer
        story.append(Paragraph("4. Data Provenance & Trust Layer", h2_style))
        disclaimer = (
            "NOTICE: Port constraints and berth physical parameters are based on officially gazetted Port Trust publications. "
            "Freight curves are generated via statistical Gradient Boosting models trained on reproducible seeded benchmarks (SIMULATED SIH DEMO DATA). "
            "Marine weather data integrates Open-Meteo services for situational awareness. This report is for strategic logistics planning and "
            "not for operational vessel navigation or contractual commitment."
        )
        story.append(Paragraph(disclaimer, ParagraphStyle('Disclaimer', parent=body_style, fontSize=8, textColor=colors.HexColor('#64748B'), leading=11)))

        doc.build(story)
        return file_path
